FROM python:3.10-slim-bullseye

WORKDIR /app

ENV DEBIAN_FRONTEND=noninteractive


RUN apt-get update && apt-get install -y --no-install-recommends gcc libpq-dev netcat-traditional docker.io && rm -rf /var/lib/apt/lists/*
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

ENV PYTHONPATH=/app

CMD ["/bin/bash", "-c", "while ! nc -z postgres 5432; do sleep 0.1; done; uvicorn main:app --host 0.0.0.0 --port 8000"]