[supervisord]
nodaemon=true

[program:provision]
command=/setup/provision.sh
startsecs=0
autorestart=false
priority=1

[program:samba]
command=/usr/sbin/samba -i --debug-stdout
autostart=true
autorestart=true
priority=10
