"""Remove internal_port from Machine

Revision ID: 2399245fc91f
Revises: 6fd645dc9628
Create Date: 2025-10-06 17:28:03.218135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2399245fc91f'
down_revision: Union[str, Sequence[str], None] = '6fd645dc9628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machines', 'internal_port')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machines', sa.Column('internal_port', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
