"""empty message

Revision ID: 61ded1ba2042
Revises: 04f45b9e96a2
Create Date: 2025-10-02 19:11:13.455997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61ded1ba2042'
down_revision: Union[str, Sequence[str], None] = '04f45b9e96a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('machines_current_user_id_fkey'), 'machines', type_='foreignkey')
    op.drop_column('machines', 'current_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machines', sa.Column('current_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('machines_current_user_id_fkey'), 'machines', 'users', ['current_user_id'], ['id'])
    # ### end Alembic commands ###
