"""Add internal_port to Machine model

Revision ID: 6fd645dc9628
Revises: 9ee5e4da5313
Create Date: 2025-10-06 17:14:38.717199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fd645dc9628'
down_revision: Union[str, Sequence[str], None] = '9ee5e4da5313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machines', sa.Column('internal_port', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machines', 'internal_port')
    # ### end Alembic commands ###
