"""empty message

Revision ID: a28e76ecf134
Revises: 61ded1ba2042
Create Date: 2025-10-02 19:27:17.935288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a28e76ecf134'
down_revision: Union[str, Sequence[str], None] = '61ded1ba2042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machines', sa.Column('current_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'machines', 'users', ['current_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'machines', type_='foreignkey')
    op.drop_column('machines', 'current_user_id')
    # ### end Alembic commands ###
