"""Remove provider and config_json from Machine

Revision ID: b602cff8c0e8
Revises: 2399245fc91f
Create Date: 2025-10-06 17:36:41.094166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b602cff8c0e8'
down_revision: Union[str, Sequence[str], None] = '2399245fc91f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machines', 'config_json')
    op.drop_column('machines', 'provider')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machines', sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('config_json', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
