"""empty message

Revision ID: 04f45b9e96a2
Revises: e0cc61357f2d
Create Date: 2025-10-02 19:01:56.941534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04f45b9e96a2'
down_revision: Union[str, Sequence[str], None] = 'e0cc61357f2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machines', sa.Column('current_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'machines', 'users', ['current_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'machines', type_='foreignkey')
    op.drop_column('machines', 'current_user_id')
    # ### end Alembic commands ###
