""""Add_is_deleted_to_Challenge_model"

Revision ID: 08ba146f3b09
Revises: 518454451669
Create Date: 2025-11-04 13:51:53.990312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08ba146f3b09'
down_revision: Union[str, Sequence[str], None] = '518454451669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenges', 'is_deleted')
    # ### end Alembic commands ###
