""""Add_is_deleted_to_Machine"

Revision ID: 0a29b7837bcb
Revises: 7ad5bc03970d
Create Date: 2025-08-09 13:35:56.399380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a29b7837bcb'
down_revision: Union[str, Sequence[str], None] = '7ad5bc03970d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machines', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machines', 'is_deleted')
    # ### end Alembic commands ###
