"""empty message

Revision ID: 28dab072cba2
Revises: bac21dc7939f
Create Date: 2025-11-04 01:32:41.100518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28dab072cba2'
down_revision: Union[str, Sequence[str], None] = 'bac21dc7939f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machines', sa.Column('provider', sa.String(), nullable=True))
    op.add_column('machines', sa.Column('operating_system', sa.String(), nullable=True))
    op.add_column('machines', sa.Column('config_json', sa.String(), nullable=True))
    op.add_column('machines', sa.Column('solves', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machines', 'solves')
    op.drop_column('machines', 'config_json')
    op.drop_column('machines', 'operating_system')
    op.drop_column('machines', 'provider')
    # ### end Alembic commands ###
