"""empty message

Revision ID: 518454451669
Revises: 472b826f5079
Create Date: 2025-11-04 13:45:52.776128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '518454451669'
down_revision: Union[str, Sequence[str], None] = '472b826f5079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('docker_image', sa.String(), nullable=True))
    op.add_column('challenges', sa.Column('ip_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenges', 'ip_address')
    op.drop_column('challenges', 'docker_image')
    # ### end Alembic commands ###
