"""empty message

Revision ID: 61002433d8cb
Revises: da6807a25ed3
Create Date: 2025-11-05 11:58:13.801046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61002433d8cb'
down_revision: Union[str, Sequence[str], None] = 'da6807a25ed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machines', sa.Column('release_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('machines', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machines', 'status')
    op.drop_column('machines', 'release_date')
    # ### end Alembic commands ###
