"""Add active_machines association table and remove current_user_id

Revision ID: 9ee5e4da5313
Revises: a28e76ecf134
Create Date: 2025-10-06 15:13:20.559279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ee5e4da5313'
down_revision: Union[str, Sequence[str], None] = 'a28e76ecf134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_machines',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'machine_id')
    )
    op.drop_constraint(op.f('machines_current_user_id_fkey'), 'machines', type_='foreignkey')
    op.drop_column('machines', 'current_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machines', sa.Column('current_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('machines_current_user_id_fkey'), 'machines', 'users', ['current_user_id'], ['id'])
    op.drop_table('active_machines')
    # ### end Alembic commands ###
