"""Refactor Machine model for generalized providers

Revision ID: a5c6a1cd0f65
Revises: 8298cea42fdd
Create Date: 2025-08-10 21:51:13.141331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5c6a1cd0f65'
down_revision: Union[str, Sequence[str], None] = '8298cea42fdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flags', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.add_column('machines', sa.Column('provider', sa.String(), nullable=True))
    op.add_column('machines', sa.Column('source_identifier', sa.String(), nullable=True))
    op.add_column('machines', sa.Column('config_json', sa.String(), nullable=True))
    op.alter_column('machines', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('machines', 'docker_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machines', sa.Column('docker_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('machines', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('machines', 'config_json')
    op.drop_column('machines', 'source_identifier')
    op.drop_column('machines', 'provider')
    op.alter_column('flags', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
