""""Add_ip_address_to_Machine"

Revision ID: cb53490fac83
Revises: 143fcc37e04c
Create Date: 2025-08-07 23:41:22.656336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb53490fac83'
down_revision: Union[str, Sequence[str], None] = '143fcc37e04c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machines', sa.Column('ip_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machines', 'ip_address')
    # ### end Alembic commands ###
