""""Update_ChallengeSubmission_model_with_challenge_flag_id"

Revision ID: da6807a25ed3
Revises: 6b00aae38f9b
Create Date: 2025-11-04 14:55:55.053071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da6807a25ed3'
down_revision: Union[str, Sequence[str], None] = '6b00aae38f9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge_submissions', sa.Column('challenge_flag_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'challenge_submissions', 'challenge_flags', ['challenge_flag_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'challenge_submissions', type_='foreignkey')
    op.drop_column('challenge_submissions', 'challenge_flag_id')
    # ### end Alembic commands ###
