"""Make source_identifier nullable

Revision ID: e0cc61357f2d
Revises: a5c6a1cd0f65
Create Date: 2025-08-10 22:07:25.074772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0cc61357f2d'
down_revision: Union[str, Sequence[str], None] = 'a5c6a1cd0f65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
