"""empty message

Revision ID: f79c88e35093
Revises: 5d30cd6352e5
Create Date: 2025-11-04 00:30:45.132814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f79c88e35093'
down_revision: Union[str, Sequence[str], None] = '5d30cd6352e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Update existing users with a default email
    op.execute("UPDATE users SET email = 'placeholder@example.com' WHERE email IS NULL")

    # Alter the column to be non-nullable
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               nullable=False,
               existing_nullable=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
