[supervisord]
nodaemon=true

[program:apache2]
command=/usr/sbin/apache2ctl -D FOREGROUND
autostart=true
autorestart=true

[program:smbd]
command=/usr/sbin/smbd --foreground --no-process-group
autostart=true
autorestart=true

[program:nmbd]
command=/usr/sbin/nmbd --foreground --no-process-group
autostart=true
autorestart=true

[program:bot]
command=python3 /opt/bot/bot.py
autostart=true
autorestart=true
